Write-Output "STRINGLN      :,....  .....'   '';"
Write-Output "STRINGLN      ,'............  ,'''"
Write-Output "STRINGLN      ;'............',..'':"
Write-Output "STRINGLN      ;'.................''"
Write-Output "STRINGLN      ;'.................''"
Write-Output "STRINGLN      ,'..................'"
Write-Output "STRINGLN      ...............'''..,"
Write-Output "STRINGLN    :;,'',;:::::,''...,cl:;"
Write-Output "STRINGLN  ,.,;;;...',;;'.;ccc:..;"
Write-Output "STRINGLN .'ldxkkk;...'..oxkkO0O..,"
Write-Output "STRINGLN;.cOOOOkkc.....'00OOkkx..''',"
Write-Output "STRINGLN',oxxddc'. ....;odddl'.':,;"
Write-Output "STRINGLN  ;.'''.....'..'.......,"
Write-Output "STRINGLN     ;,,,,;ooddxl:;;:ccl"
Write-Output "STRINGLN      oc:cdkkOOOOko:clo"
Write-Output "STRINGLN      OkoxkkkkkkOOOkox0"
Write-Output "STRINGLN      OOOOOOkkkkkkOO000"
Write-Output "STRINGLN      OOOOOOkkkkkkkOO00"
Write-Output "STRINGLN      OOOOOOkkkkkkkOOOl"
Write-Output "STRINGLN      OOOOOOkkkkkkkkOOO0c:;;,,,',',:"
Write-Output "STRINGLN     OOOOOOkkkkkkkkkkkxx............'"
Write-Output "STRINGLN     kOOOOOkkkkkkkkkxxl' .............'"
Write-Output "STRINGLN    ,',xOOOkkkkkkkkk'..................."
Write-Output "STRINGLN  :..;kOOOOkkkkkkkkkk,.................."
Write-Output "STRINGLN :...xOOOOOkkkkkkkkkkd.................."
Read-Host -Prompt "Press Enter to continue"
